-- ex1
SELECT NAME FROM CITY
WHERE COUNTRYCODE = 'USA' AND POPULATION > 120000; 

-- ex2
SELECT * FROM CITY
WHERE COUNTRYCODE = 'JPN';

-- ex3
SELECT CITY, STATE FROM STATION;

-- ex4
SELECT DISTINCT CITY FROM STATION
WHERE CITY LIKE 'A%' OR CITY LIKE 'E%' OR CITY LIKE 'I%'  OR CITY LIKE 'O%' OR CITY LIKE 'U%'; 

-- ex5
SELECT DISTINCT CITY FROM STATION
WHERE CITY LIKE '%A' OR CITY LIKE '%E' OR CITY LIKE '%I'  OR CITY LIKE '%O' OR CITY LIKE '%U'; 

-- ex6
SELECT DISTINCT CITY FROM STATION
WHERE NOT (CITY LIKE 'A%' OR CITY LIKE 'E%' OR CITY LIKE 'I%'  OR CITY LIKE 'O%' OR CITY LIKE 'U%'); 

-- ex7
